version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./99prozent.ch/templates:/usr/src/app/custom/templates/99prozent.ch
      - ./99prozent.ch/static:/usr/src/app/custom/static/99prozent.ch
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  cache:
    image: memcached:alpine
  celery:
    build: .
    command: celery -A juso worker --loglevel DEBUG
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
  redis:
    image: redis
    expose:
      - 6379
  db:
    image: postgres:13-alpine
    volumes:
      - postgres13_data:/var/lib/postgresql/data/
      - .:/tmp
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres13_data:
