# Generated by Django 3.0.3 on 2020-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20200215_2346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(default=0, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="lng",
            field=models.FloatField(default=0, verbose_name="longitude"),
        ),
    ]
