# Generated by Django 3.0.3 on 2020-03-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_team_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='columns',
        ),
    ]
