# Generated by Django 3.0.3 on 2020-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_merge_20200324_2216"),
    ]

    operations = [
        migrations.AddField(
            model_name="divider",
            name="header",
            field=models.BooleanField(default=False, verbose_name="header"),
        ),
    ]
