# Generated by Django 3.0.3 on 2020-04-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_auto_20200413_1405"),
        ("events", "0014_auto_20200331_1609"),
    ]

    operations = []
