# Generated by Django 3.0.5 on 2020-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_auto_20200508_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="fullwidth",
            field=models.BooleanField(default=False,
                                      verbose_name="full width"),
        ),
    ]
