# Generated by Django 3.0.5 on 2020-05-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0009_auto_20200507_1758"),
        ("forms", "0018_auto_20200509_1826"),
        ("events", "0026_auto_20200510_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventplugin",
            name="sections",
            field=models.ManyToManyField(
                blank=True, related_name="events_eventplugin", to="sections.Section"
            ),
        ),
        migrations.AlterField(
            model_name="formplugin",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_formplugin",
                to="forms.Form",
                verbose_name="Formular",
            ),
        ),
    ]
