# Generated by Django 3.0.5 on 2020-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_auto_20200523_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_physical",
            field=models.BooleanField(default=True, verbose_name="is physical"),
        ),
    ]
