# Generated by Django 3.0.5 on 2020-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0044_formentrycounterplugin_template_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentrycounterplugin",
            name="prefix",
            field=models.CharField(blank=True,
                                   max_length=100,
                                   verbose_name="pefix"),
        ),
        migrations.AddField(
            model_name="formentrycounterplugin",
            name="suffix",
            field=models.CharField(blank=True,
                                   max_length=100,
                                   verbose_name="suffix"),
        ),
    ]
