# Generated by Django 3.0.5 on 2020-07-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_formentrycounterplugin_aggregate_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="author",),
    ]
