# Generated by Django 3.2.4 on 2021-06-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_auto_20210624_1224'),
        ('events', '0055_auto_20210624_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=3)),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_testimonialplugin', to='testimonials.campaign', verbose_name='campaign')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_testimonialplugin_set', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
