# Generated by Django 3.2.4 on 2021-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_testimonialplugin_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialplugin',
            name='button_text',
            field=models.CharField(default='Einreichen', max_length=280),
        ),
        migrations.AddField(
            model_name='testimonialplugin',
            name='create_url',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
