# Generated by Django 3.2.15 on 2026-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_testimonialplugin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='template_key',
            field=models.CharField(choices=[('default', 'Default'), ('feature_top', 'Feature_Top')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
