# Generated by Django 4.2.30 on 2026-07-04 20:02

from django.db import migrations, models
import feincms3.utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_alter_articleplugin_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AddField(
            model_name='external',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='image',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AddField(
            model_name='locationimage',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AlterField(
            model_name='articleplugin',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='template_key',
            field=models.CharField(choices=[('', '')], default='default', max_length=100, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to=feincms3.utils.upload_to, verbose_name='image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='location',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=feincms3.utils.upload_to, verbose_name='image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
