# Generated by Django 3.0.5 on 2020-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
