# Generated by Django 3.2.4 on 2021-06-24 08:57

from django.db import migrations, models
import juso.testimonials.models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20210624_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='secret',
            field=models.CharField(default=juso.testimonials.models.generate_secret, max_length=280, verbose_name='secret'),
        ),
    ]
