# Generated by Django 3.2.4 on 2021-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_testimonial_secret'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(fields=('campaign', 'email'), name='unique_email_per_campaign'),
        ),
    ]
