# Generated by Django 3.2.4 on 2021-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_testimonial_unique_email_per_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='create_text',
            field=models.TextField(blank=True, verbose_name='create text'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='create_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='create title'),
        ),
    ]
