# Generated by Django 3.2.4 on 2021-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_auto_20210624_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='statement',
            field=models.TextField(max_length=240, verbose_name='statement'),
        ),
    ]
