# Generated by Django 3.2.4 on 2021-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_alter_testimonial_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='statement',
            field=models.TextField(max_length=280, verbose_name='statement'),
        ),
    ]
