# Generated by Django 3.2.15 on 2026-07-04 15:02

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_alter_testimonial_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='first_name',
            field=models.CharField(max_length=180, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=imagefield.fields.ImageField(height_field='image_height', upload_to='', verbose_name='image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='last_name',
            field=models.CharField(max_length=180, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=180, verbose_name='title'),
        ),
    ]
