# Generated by Django 3.0.3 on 2020-05-02 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feincms3.cleanse
import imagefield.fields
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20200215_1901'), ('blog', '0003_auto_20200215_2128'), ('blog', '0004_auto_20200215_2346'), ('blog', '0005_button'), ('blog', '0006_auto_20200324_2039'), ('blog', '0007_divider_header_team'), ('blog', '0008_auto_20200324_2144'), ('blog', '0005_article_translations'), ('blog', '0006_namespace_translations'), ('blog', '0007_auto_20200302_1952'), ('blog', '0008_auto_20200302_1955'), ('blog', '0009_merge_20200324_2216'), ('blog', '0010_eventplugin'), ('blog', '0011_auto_20200328_1540'), ('blog', '0010_divider_header'), ('blog', '0012_merge_20200328_1757'), ('blog', '0013_glossaryrichtext'), ('blog', '0014_glossaryrichtext_update_glossary'), ('blog', '0015_auto_20200429_1653'), ('blog', '0016_auto_20200429_1939')]

    initial = True

    dependencies = [
        ('forms', '0012_auto_20200426_1301'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0012_merge_20200324_2216'),
        ('sections', '0005_category_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sections', '0001_initial'),
        ('sections', '0003_auto_20200302_1952'),
        ('glossary', '0003_auto_20200416_2112'),
        ('people', '0007_auto_20200324_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Used for Open Graph and other meta tags.', max_length=200, verbose_name='title')),
                ('meta_description', models.TextField(blank=True, help_text='Override the description for this page.', verbose_name='description')),
                ('meta_image', imagefield.fields.ImageField(blank=True, height_field='meta_image_height', help_text='Set the Open Graph image.', upload_to='meta/%Y/%m', verbose_name='image', width_field='meta_image_width')),
                ('meta_canonical', models.URLField(blank=True, help_text='If you need this you probably know.', verbose_name='canonical URL')),
                ('meta_author', models.CharField(blank=True, help_text='Override the author meta tag.', max_length=200, verbose_name='author')),
                ('meta_robots', models.CharField(blank=True, help_text='Override the robots meta tag.', max_length=200, verbose_name='robots')),
                ('meta_image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('meta_image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('meta_image_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
                ('template_key', models.CharField(choices=[('default', 'Default'), ('sidebar-right', 'Sidebar-Right'), ('sidebar-left', 'Sidebar-Left'), ('fullwidth', 'Fullwidth')], default='default', max_length=100, verbose_name='template')),
                ('language_code', models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='de', max_length=10, verbose_name='language')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('edited_date', models.DateTimeField(auto_now=True, verbose_name='edited at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='de', max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('translations', models.ManyToManyField(blank=True, related_name='_namespace_translations_+', to='blog.NameSpace')),
            ],
            options={
                'verbose_name': 'name space',
                'verbose_name_plural': 'name spaces',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', feincms3.cleanse.CleansedRichTextField(verbose_name='text')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_richtext_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text='The content will be inserted directly into the page. It is VERY important that the HTML snippet is well-formed!', verbose_name='HTML')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_html_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'HTML',
                'verbose_name_plural': 'HTML',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_external_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'external content',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='downloads/', verbose_name='Datei')),
                ('download_text', models.CharField(max_length=200, verbose_name='download text')),
                ('link_classes', models.CharField(blank=True, max_length=200, verbose_name='link classes (css)')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_download_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'download',
                'verbose_name_plural': 'downloads',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.NameSpace', verbose_name='namespace'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('teams/default.html', 'default')], default='teams/default.html', max_length=100)),
                ('columns', models.CharField(choices=[('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], default='three', max_length=10, verbose_name='columns')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_team_set', to='blog.Article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.Team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagefield.fields.ImageField(height_field='height', upload_to='images/%Y/%m', verbose_name='image', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='image width')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='image height')),
                ('ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20, verbose_name='primary point of interest')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image_set', to='blog.Article')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_article_translations_+', to='blog.Article'),
        ),
        migrations.CreateModel(
            name='EventPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='de', max_length=10, verbose_name='language')),
                ('count', models.IntegerField(default=3, verbose_name='count')),
                ('template_key', models.CharField(choices=[('events/plugins/default.html', 'default')], default='events/plugins/default.html', max_length=100)),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='sections.Category', verbose_name='category')),
                ('events', models.ManyToManyField(blank=True, related_name='_eventplugin_events_+', related_query_name='+', to='events.Event', verbose_name='events')),
                ('namespace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='events.NameSpace', verbose_name='namespace')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_eventplugin_set', to='blog.Article')),
                ('sections', models.ManyToManyField(blank=True, related_name='_eventplugin_sections_+', related_query_name='+', to='sections.Section')),
                ('translations', models.ManyToManyField(blank=True, related_name='_eventplugin_translations_+', to='blog.EventPlugin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', feincms3.cleanse.CleansedRichTextField(verbose_name='text')),
                ('glossary_text', models.TextField(blank=True)),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('entries', models.ManyToManyField(related_name='blog_glossaryrichtext_related', related_query_name='blog_glossaryrichtexts', to='glossary.Entry', verbose_name='entries')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_glossaryrichtext_set', to='blog.Article')),
                ('update_glossary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'glossary text',
            },
        ),
        migrations.CreateModel(
            name='ArticlePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='de', max_length=10, verbose_name='language')),
                ('count', models.IntegerField(default=3, verbose_name='count')),
                ('template_key', models.CharField(choices=[('blog/plugins/default.html', 'default')], default='blog/plugins/default.html', max_length=100)),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='_articleplugin_articles_+', related_query_name='+', to='blog.Article', verbose_name='articles')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sections.Category', verbose_name='category')),
                ('namespace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.NameSpace', verbose_name='namespace')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articleplugin_set', to='blog.Article')),
                ('sections', models.ManyToManyField(blank=True, related_name='_articleplugin_sections_+', related_query_name='+', to='sections.Section')),
                ('translations', models.ManyToManyField(blank=True, related_name='_articleplugin_translations_+', to='blog.ArticlePlugin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='forms.Form', verbose_name='form')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_formplugin_set', to='blog.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=240, verbose_name='Text')),
                ('color', models.CharField(blank=True, choices=[('red', 'red')], max_length=20)),
                ('style', models.CharField(blank=True, choices=[('', 'none'), ('secondary', 'secondary')], default='', max_length=20, verbose_name='style')),
                ('target', models.CharField(max_length=800, verbose_name='Ziel')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_button_set', to='blog.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=imagefield.fields.ImageField(blank=True, height_field='header_image_height', null=True, upload_to='', verbose_name='header image', width_field='header_image_width'),
        ),
        migrations.AddField(
            model_name='article',
            name='header_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='header_image_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='header_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
