# Generated by Django 3.0.3 on 2020-02-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200215_2128"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-publication_date"],
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
    ]
