# Generated by Django 3.0.3 on 2020-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200215_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='translations',
            field=models.ManyToManyField(related_name='_article_translations_+', to='blog.Article', verbose_name='translations'),
        ),
    ]
