# Generated by Django 3.0.3 on 2020-02-10 21:39

import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='namespace',
            options={'ordering': ['slug'], 'verbose_name': 'name space', 'verbose_name_plural': 'name spaces'},
        ),
        migrations.AddField(
            model_name='article',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Override the author meta tag.', max_length=200, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_canonical',
            field=models.URLField(blank=True, help_text='If you need this you probably know.', verbose_name='canonical URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Override the description for this page.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image',
            field=imagefield.fields.ImageField(blank=True, height_field='meta_image_height', help_text='Set the Open Graph image.', upload_to='meta/%Y/%m', verbose_name='image', width_field='meta_image_width'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_robots',
            field=models.CharField(blank=True, help_text='Override the robots meta tag.', max_length=200, verbose_name='robots'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Used for Open Graph and other meta tags.', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
    ]
