# Generated by Django 3.0.3 on 2020-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200210_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='template_key',
            field=models.CharField(choices=[('default', 'default'), ('sidebar', 'sidebar')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
