# Generated by Django 3.0.3 on 2020-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_namespace_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_namespace_translations_+', to='blog.NameSpace'),
        ),
    ]
