# Generated by Django 3.0.3 on 2020-02-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200212_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='template_key',
            field=models.CharField(choices=[('default', 'Default'), ('sidebar-right', 'Sidebar-Right'), ('sidebar-left', 'Sidebar-Left'), ('fullwidth', 'Fullwidth')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
