# Generated by Django 3.0.3 on 2020-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200302_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_article_translations_+', to='blog.Article'),
        ),
    ]
