# Generated by Django 3.0.3 on 2020-03-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20200324_2144"),
        ("blog", "0008_auto_20200302_1955"),
    ]

    operations = []
