# Generated by Django 3.0.3 on 2020-03-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_eventplugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventplugin",
            name="template_key",
            field=models.CharField(
                choices=[("events/plugins/default.html", "default")],
                default="events/plugins/default.html",
                max_length=100,
            ),
        ),
    ]
