# Generated by Django 3.0.3 on 2020-03-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_divider_header"),
        ("blog", "0011_auto_20200328_1540"),
    ]

    operations = []
