# Generated by Django 3.0.5 on 2020-05-05 21:51

import django.db.models.deletion
import django.utils.timezone
import imagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0018_auto_20200429_1943"),
        ("people", "0009_merge_20200324_2216"),
        ("sections", "0007_auto_20200502_2048"),
        ("glossary", "0005_auto_20200505_2351"),
        ("forms", "0013_auto_20200429_1939"),
        ("blog", "0017_auto_20200502_2016"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-publication_date"],
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikel",
            },
        ),
        migrations.AlterModelOptions(
            name="download",
            options={"verbose_name": "Download", "verbose_name_plural": "Downloads"},
        ),
        migrations.AlterModelOptions(
            name="glossaryrichtext", options={"verbose_name": "Glossar Text"},
        ),
        migrations.AlterModelOptions(
            name="namespace",
            options={
                "ordering": ["slug"],
                "verbose_name": "Namensraum",
                "verbose_name_plural": "Namensräume",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor*in",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.Category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Erstellungsdatum"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="edited_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Bearbeitungsdatum"),
        ),
        migrations.AlterField(
            model_name="article",
            name="header_image",
            field=imagefield.fields.ImageField(
                blank=True,
                height_field="header_image_height",
                null=True,
                upload_to="",
                verbose_name="Header Bild",
                width_field="header_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="namespace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.NameSpace",
                verbose_name="Namensraum",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Publikationsdatum"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sections.Section",
                verbose_name="Sektion",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("default", "Standard"),
                    ("sidebar-right", "Sidebar-Right"),
                    ("sidebar-left", "Sidebar-Left"),
                    ("fullwidth", "Fullwidth"),
                ],
                default="default",
                max_length=100,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="articleplugin",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="_articleplugin_articles_+",
                related_query_name="+",
                to="blog.Article",
                verbose_name="Artikel",
            ),
        ),
        migrations.AlterField(
            model_name="articleplugin",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sections.Category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="articleplugin",
            name="count",
            field=models.IntegerField(default=3, verbose_name="Anzahl"),
        ),
        migrations.AlterField(
            model_name="articleplugin",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.NameSpace",
                verbose_name="Namensraum",
            ),
        ),
        migrations.AlterField(
            model_name="button",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[("", "keine"), ("secondary", "sekundär")],
                default="",
                max_length=20,
                verbose_name="Styl",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="download_text",
            field=models.CharField(max_length=200, verbose_name="Download Text"),
        ),
        migrations.AlterField(
            model_name="download",
            name="link_classes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Link Klassen (css)"
            ),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="sections.Category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="count",
            field=models.IntegerField(default=3, verbose_name="Anzahl"),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="_eventplugin_events_+",
                related_query_name="+",
                to="events.Event",
                verbose_name="Events",
            ),
        ),
        migrations.AlterField(
            model_name="eventplugin",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to="events.NameSpace",
                verbose_name="Namensraum",
            ),
        ),
        migrations.AlterField(
            model_name="formplugin",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="forms.Form",
                verbose_name="Formular",
            ),
        ),
        migrations.AlterField(
            model_name="glossaryrichtext",
            name="entries",
            field=models.ManyToManyField(
                related_name="blog_glossaryrichtext_related",
                related_query_name="blog_glossaryrichtexts",
                to="glossary.Entry",
                verbose_name="Einträge",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="team",
            name="columns",
            field=models.CharField(
                choices=[("two", "2"), ("three", "3"), ("four", "4"), ("five", "5")],
                default="three",
                max_length=10,
                verbose_name="Spalten",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="people.Team",
                verbose_name="Team",
            ),
        ),
    ]
