# Generated by Django 3.0.5 on 2020-05-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_auto_20200507_1758"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleplugin",
            options={
                "verbose_name": "Artikel plugin",
                "verbose_name_plural": "Artikel plugin",
            },
        ),
        migrations.AlterModelOptions(
            name="eventplugin",
            options={
                "verbose_name": "event plugin",
                "verbose_name_plural": "Event plugins",
            },
        ),
    ]
