# Generated by Django 3.0.5 on 2020-05-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200509_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespacemapping',
            name='wp_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='blog.WPImport'),
        ),
    ]
