# Generated by Django 3.0.5 on 2020-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_auto_20200509_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=180, verbose_name="Slug"),
        ),
    ]
