# Generated by Django 3.0.5 on 2020-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_auto_20200510_1144"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplugin",
            name="title",
            field=models.CharField(blank=True, max_length=180, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="wpimport",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
