# Generated by Django 3.0.5 on 2020-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0037_articleplugin_structured_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_video",
            field=models.FileField(
                blank=True,
                help_text="Set the Open Graph video.",
                upload_to="meta/video/%Y/%m",
                verbose_name="video",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_video_height",
            field=models.IntegerField(default=1080,
                                      verbose_name="video height"),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_video_width",
            field=models.IntegerField(default=1920,
                                      verbose_name="video width"),
        ),
    ]
