# Generated by Django 3.0.5 on 2020-07-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0046_auto_20200712_1711"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
