# Generated by Django 3.0.5 on 2020-07-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_auto_20200523_1748"),
        ("blog", "0047_remove_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
                verbose_name="author",
            ),
        ),
    ]
