# Generated by Django 3.0.5 on 2020-07-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0049_auto_20200721_1045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventplugin",
            name="namespace",
        ),
    ]
