# Generated by Django 3.2.4 on 2021-06-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20200828_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_card_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player_width',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_twitter_site',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_width',
        ),
    ]
