# Generated by Django 3.2.4 on 2021-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_testimonialplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialplugin',
            name='css_class',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
