# Generated by Django 5.2.15 on 2026-07-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_external_alternative_text_external_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_card_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_player_width',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_twitter_site',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_video_width',
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image_alternative_text',
            field=models.CharField(blank=True, default='', help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_author',
            field=models.CharField(blank=True, default='', help_text='Override the author meta tag.', max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_canonical',
            field=models.URLField(blank=True, default='', help_text='If you need this you probably know.', verbose_name='canonical URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Override the description for this page.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_image',
            field=models.ImageField(blank=True, default='', height_field='meta_image_height', help_text='Set the Open Graph image.', upload_to='meta/%Y/%m', verbose_name='image', width_field='meta_image_width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_robots',
            field=models.CharField(blank=True, default='', help_text='Override the robots meta tag.', max_length=200, verbose_name='robots'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Used for Open Graph and other meta tags.', max_length=200, verbose_name='title'),
        ),
    ]
