# Generated by Django 3.0.5 on 2020-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0004_entry_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="auto_pattern",
            field=models.BooleanField(
                default=True, verbose_name="automatisches Muster"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="pattern",
            field=models.CharField(blank=True, max_length=200, verbose_name="Muster"),
        ),
    ]
