# Generated by Django 3.0.5 on 2020-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0005_auto_20200505_2351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="auto_pattern",
            field=models.BooleanField(default=True,
                                      verbose_name="auto-pattern"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="name",
            field=models.CharField(max_length=40, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="pattern",
            field=models.CharField(blank=True,
                                   max_length=200,
                                   verbose_name="pattern"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
    ]
