# Generated by Django 3.0.5 on 2020-07-06 15:52

import feincms3.cleanse
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0006_auto_20200523_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="intro",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=feincms3.cleanse.CleansedRichTextField(blank=True),
        ),
    ]
