# Generated by Django 4.2.30 on 2026-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_auto_20200706_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='glossary.entry'),
        ),
    ]
