# Generated by Django 3.0.5 on 2020-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_form_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fullwidth',
            field=models.BooleanField(default=False, verbose_name='full width'),
            preserve_default=False,
        ),
    ]
