# Generated by Django 3.0.5 on 2020-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_form_fullwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=180, verbose_name='Slug'),
        ),
    ]
