# Generated by Django 3.0.5 on 2020-05-23 15:48

import django.db.models.deletion
import django.utils.timezone
import imagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0009_auto_20200507_1758"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0018_auto_20200509_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.Category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="form",
            name="edited_date",
            field=models.DateTimeField(auto_now=True,
                                       verbose_name="edited at"),
        ),
        migrations.AlterField(
            model_name="form",
            name="header_image",
            field=imagefield.fields.ImageField(
                blank=True,
                height_field="header_image_height",
                null=True,
                upload_to="",
                verbose_name="header image",
                width_field="header_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="publication_date",
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name="publication date"),
        ),
        migrations.AlterField(
            model_name="form",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sections.Section",
                verbose_name="section",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(max_length=180, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="form",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
