# Generated by Django 3.0.5 on 2020-06-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0024_auto_20200626_1201"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RichText",
        ),
    ]
