# Generated by Django 3.0.5 on 2020-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_auto_20200701_0932"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="unique",
            field=models.BooleanField(
                default=False,
                help_text=
                "restricts people to only submit one value for this form",
                verbose_name="uniques",
            ),
        ),
    ]
