# Generated by Django 3.0.5 on 2020-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_formfield_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="unique_error",
            field=models.CharField(
                blank=True,
                help_text="error that is displayed if value already exists",
                max_length=180,
                verbose_name="unique error",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="unique",
            field=models.BooleanField(
                default=False,
                help_text=
                "restricts people to only submit one value for this form",
                verbose_name="unique",
            ),
        ),
    ]
