# Generated by Django 3.0.5 on 2020-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0028_auto_20200701_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentryvalue",
            name="int_value",
            field=models.IntegerField(default=0, verbose_name="int value"),
        ),
    ]
