# Generated by Django 3.0.5 on 2020-07-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0029_formentryvalue_int_value"),
    ]

    operations = [
        migrations.RemoveField(model_name="form", name="author",),
    ]
