# Generated by Django 3.1 on 2020-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_form_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formentryvalue",
            name="value",
            field=models.TextField(blank=True, null=True,
                                   verbose_name="value"),
        ),
    ]
