# Generated by Django 3.1 on 2020-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_auto_20200811_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="email",
            field=models.CharField(blank=True,
                                   max_length=1200,
                                   verbose_name="e-mail"),
        ),
    ]
