# Generated by Django 3.1 on 2020-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0034_form_webhook_dict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="webhook_dict",
            field=models.JSONField(default=dict, verbose_name="webhook dict"),
        ),
    ]
