# Generated by Django 3.1 on 2020-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_form_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='webhook_dict',
            field=models.JSONField(blank=True, null=True, verbose_name='webhook dict'),
        ),
    ]
