# Generated by Django 3.1 on 2020-09-13 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0040_auto_20200825_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="submission_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
