# Generated by Django 3.1 on 2020-09-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0041_formentry_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="linked_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_forms",
                to="forms.form",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="linking_field_slug",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
