# Generated by Django 3.1.4 on 2020-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_auto_20200923_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='disallow_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('long_text', 'long text'), ('email', 'email'), ('boolean', 'boolean'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time'), ('decimal', 'decimal'), ('file', 'file'), ('image', 'image'), ('int', 'integer'), ('choice', 'choice'), ('multi', 'multiple choice'), ('url', 'url'), ('hidden', 'hidden'), ('section', 'section'), ('honeypot', 'honeypot')], max_length=140, verbose_name='type'),
        ),
    ]
