# Generated by Django 3.1 on 2020-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0044_webhook_webhookfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookfield",
            name="field_converter",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="webhookfield",
            name="field_converter_args",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
