# Generated by Django 3.1 on 2020-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0045_auto_20201121_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="webhooks",
            field=models.ManyToManyField(blank=True, to="forms.Webhook"),
        ),
    ]
