# Generated by Django 3.1 on 2020-11-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_form_webhooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='region',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='ordering',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AlterField(
            model_name='webhookfield',
            name='field_converter',
            field=models.CharField(
                blank=True,
                help_text='apply a converter on the user input',
                max_length=200),
        ),
        migrations.AlterField(
            model_name='webhookfield',
            name='field_converter_args',
            field=models.CharField(blank=True,
                                   help_text='arguments for the converter',
                                   max_length=200),
        ),
        migrations.AlterField(
            model_name='webhookfield',
            name='form_slug',
            field=models.SlugField(help_text='slug of the field in the form'),
        ),
        migrations.AlterField(
            model_name='webhookfield',
            name='webhook_slug',
            field=models.CharField(
                help_text='name of the field in the request to the webhook',
                max_length=200),
        ),
    ]
