# Generated by Django 3.1.4 on 2021-01-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0047_auto_20201122_1337'),
        ('forms', '0044_auto_20201206_2310'),
    ]

    operations = [
    ]
