# Generated by Django 3.2.4 on 2021-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_merge_20210131_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='meta_card_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_player',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_player_height',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_player_width',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_twitter_site',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_video',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_video_height',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_video_url',
        ),
        migrations.RemoveField(
            model_name='form',
            name='meta_video_width',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='provide the options for a choice field', verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='additional info for people', max_length=240, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='initial',
            field=models.TextField(blank=True, help_text='initial value for this field', max_length=240, verbose_name='initial'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('long_text', 'long text'), ('email', 'email'), ('boolean', 'boolean'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time'), ('decimal', 'decimal'), ('file', 'file'), ('image', 'image'), ('int', 'integer'), ('choice', 'choice'), ('multi', 'multiple choice'), ('url', 'url'), ('hidden', 'hidden'), ('section', 'section'), ('honeypot', 'honeypot'), ('captcha', 'Captcha')], help_text='type of the input field', max_length=140, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='name',
            field=models.CharField(help_text='label for form field', max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(help_text='force people to provide this value', verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='size',
            field=models.TextField(choices=[('one', 'one'), ('one-half', 'one half'), ('one-third', 'one third'), ('one-fourth', 'one fouth'), ('three-fourths', 'thre fourths'), ('two-thirds', 'two thirds')], default='one', help_text='proportion of the field', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='slug',
            field=models.SlugField(help_text='name that will be used in export headings'),
        ),
    ]
