# Generated by Django 3.2.15 on 2026-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0050_auto_20210624_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='template_key',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
