# Generated by Django 4.2.30 on 2026-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0051_alter_form_template_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='forms.form'),
        ),
    ]
