# Generated by Django 4.2.30 on 2026-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0052_alter_form_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='form',
            name='template_key',
            field=models.CharField(choices=[('', '')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
