# Generated by Django 3.0.3 on 2020-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.ManyToManyField(related_name='_category_translations_+', to='sections.Category'),
        ),
    ]
