# Generated by Django 3.0.3 on 2020-02-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_tags'),
        ('sections', '0002_auto_20200209_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
