# Generated by Django 3.0.3 on 2020-02-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
