# Generated by Django 3.0.3 on 2020-02-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feincms3_sites', '0004_site_is_active'),
        ('sections', '0004_auto_20200210_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='feincms3_sites.Site', verbose_name='Webseite'),
        ),
    ]
