# Generated by Django 3.0.5 on 2020-05-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_auto_20200505_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
