# Generated by Django 4.2.30 on 2026-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0016_auto_20210624_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='sections.category'),
        ),
    ]
