# Generated by Django 3.0.3 on 2020-02-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_auto_20200215_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="application",
            field=models.CharField(
                blank=True,
                choices=[("blog", "blog"), ("people", "people")],
                max_length=20,
                verbose_name="application",
            ),
        ),
    ]
