# Generated by Django 3.0.3 on 2020-02-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200210_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_landing_page',
            field=models.BooleanField(default=False, verbose_name='is landing page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[('default', 'Default'), ('sidebar-right', 'Sidebar-Right'), ('sidebar-left', 'Sidebar-Left'), ('fullwidth', 'Fullwidth')], default='default', max_length=100, verbose_name='template'),
        ),
    ]
