# Generated by Django 3.0.3 on 2020-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_page_all_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="translations",
            field=models.ManyToManyField(
                related_name="_page_translations_+", to="pages.Page"
            ),
        ),
    ]
