# Generated by Django 3.0.3 on 2020-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_page_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="translations",
            field=models.ManyToManyField(
                blank=True, related_name="_page_translations_+", to="pages.Page"
            ),
        ),
    ]
