# Generated by Django 3.0.3 on 2020-03-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_image_title"),
        ("pages", "0009_auto_20200302_1952"),
    ]

    operations = []
