# Generated by Django 3.0.3 on 2020-03-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_auto_20200328_1540"),
        ("pages", "0019_divider_header"),
    ]

    operations = []
