# Generated by Django 3.0.3 on 2020-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_formplugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="application",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blog", "blog"),
                    ("people", "people"),
                    ("events", "events"),
                    ("categories", "categories"),
                    ("forms", "forms"),
                ],
                max_length=20,
                verbose_name="application",
            ),
        ),
    ]
