# Generated by Django 3.0.3 on 2020-04-16 20:32

from django.db import migrations, models
import django.db.models.deletion
import feincms3.cleanse


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
        ('pages', '0026_auto_20200413_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', feincms3.cleanse.CleansedRichTextField(verbose_name='text')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('entries', models.ManyToManyField(to='glossary.Entry', verbose_name='entries')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_glossaryrichtext_set', to='pages.Page')),
            ],
            options={
                'verbose_name': 'glossary text',
            },
        ),
    ]
