# Generated by Django 3.0.3 on 2020-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_glossaryrichtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryrichtext',
            name='glossary_text',
            field=models.TextField(blank=True),
        ),
    ]
