# Generated by Django 3.0.3 on 2020-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0034_auto_20200429_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="in_meta",
            field=models.BooleanField(default=False, verbose_name="in meta menu"),
        ),
        migrations.AddField(
            model_name="page",
            name="is_navigation",
            field=models.BooleanField(default=False, verbose_name="display navigation"),
        ),
    ]
