# Generated by Django 3.0.5 on 2020-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0042_auto_20200509_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="application",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blog", "blog"),
                    ("people", "people"),
                    ("events", "events"),
                    ("categories", "categories"),
                    ("glossary", "glossary"),
                    ("collection", "collection"),
                ],
                max_length=20,
                verbose_name="application",
            ),
        ),
    ]
