# Generated by Django 3.0.5 on 2020-05-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_button_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplugin',
            name='all_articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Page', verbose_name='page with all events'),
        ),
        migrations.AddField(
            model_name='eventplugin',
            name='all_articles_override',
            field=models.CharField(blank=True, max_length=180, verbose_name='all events link text'),
        ),
        migrations.AlterField(
            model_name='button',
            name='align',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('center', 'center'), ('right', 'right'), ('block', 'block')], max_length=30, verbose_name='alignment'),
        ),
    ]
