# Generated by Django 3.0.5 on 2020-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0054_articleplugin_structured_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="logo",
            field=models.TextField(blank=True, verbose_name="logo"),
        ),
    ]
