# Generated by Django 3.0.5 on 2020-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0056_auto_20200605_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="css_vars",
            field=models.TextField(blank=True, verbose_name="css vars"),
        ),
    ]
