# Generated by Django 3.0.5 on 2020-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_auto_20200626_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
