# Generated by Django 3.0.5 on 2020-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0064_auto_20200701_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentrycounterplugin",
            name="prefix_missing",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="pefix missing"
            ),
        ),
        migrations.AddField(
            model_name="formentrycounterplugin",
            name="suffix_missing",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="suffix missing"
            ),
        ),
    ]
