# Generated by Django 3.0.5 on 2020-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0065_auto_20200701_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="formentrycounterplugin",
            name="aggregate_field",
            field=models.SlugField(
                blank=True,
                help_text="use if you don't want the count of entries, but the sum of a field",
                verbose_name="aggregate field",
            ),
        ),
    ]
