# Generated by Django 3.0.5 on 2020-07-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0066_formentrycounterplugin_aggregate_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationPlugin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "pages",
                    models.ManyToManyField(
                        related_name="_navigationplugin_pages_+",
                        to="pages.Page"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages_navigationplugin_set",
                        to="pages.Page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
