# Generated by Django 3.0.5 on 2020-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0067_navigationplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="fonts",
            field=models.TextField(default="klima\nmontserrat",
                                   verbose_name="fonts"),
        ),
    ]
