# Generated by Django 3.1 on 2020-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0076_auto_20200809_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorylinking",
            name="ohter_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="pages.page",
            ),
        ),
    ]
