# Generated by Django 3.1 on 2020-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0077_categorylinking_ohter_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categorylinking", old_name="ohter_site", new_name="other_site",
        ),
    ]
