# Generated by Django 3.1 on 2020-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0082_votingrecommendationplugin"),
    ]

    operations = []
