# Generated by Django 4.2.30 on 2026-07-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_alter_category_translations'),
        ('testimonials', '0009_alter_campaign_and_testimonial_verbose_names'),
        ('events', '0061_alter_articleplugin_articles_and_more'),
        ('blog', '0061_alter_article_translations_and_more'),
        ('glossary', '0008_alter_entry_translations'),
        ('forms', '0052_alter_form_translations'),
        ('pages', '0091_alter_page_template_key_and_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleplugin',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='blog.article', verbose_name='articles'),
        ),
        migrations.AlterField(
            model_name='articleplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='articleplugin',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='sections.section'),
        ),
        migrations.AlterField(
            model_name='articleplugin',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='pages.articleplugin'),
        ),
        migrations.AlterField(
            model_name='button',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='candidatureplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='download',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='+', related_query_name='+', to='events.event', verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='sections.section'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='pages.eventplugin'),
        ),
        migrations.AlterField(
            model_name='external',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='formentrycounterplugin',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='forms.form', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='formentrycounterplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='forms.form', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='glossaryrichtext',
            name='entries',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='glossary.entry', verbose_name='entries'),
        ),
        migrations.AlterField(
            model_name='glossaryrichtext',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='html',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='navigationplugin',
            name='pages',
            field=models.ManyToManyField(related_name='+', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='navigationplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='testimonialplugin',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='testimonials.campaign', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='testimonialplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='votingrecommendationplugin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page'),
        ),
    ]
