# Generated by Django 4.2.30 on 2026-07-04 20:01

from django.conf import settings
from django.db import migrations, models
import feincms3.utils


def backfill_page_type(apps, schema_editor):
    # feincms3 page types merge the old application + template_key fields into
    # page_type. App pages keep their application key; all others keep the
    # template key. Done before the old columns are dropped below.
    Page = apps.get_model("pages", "Page")
    Page.objects.exclude(application="").update(page_type=models.F("application"))
    Page.objects.filter(application="").update(page_type=models.F("template_key"))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FEINCMS3_SITES_SITE_MODEL),
        ('pages', '0092_alter_articleplugin_articles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position'], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_page_for_path',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='pages_page_path_7e204f_idx',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='pages_page_is_land_8ba6f0_idx',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='app_instance_namespace',
            new_name='app_namespace',
        ),
        migrations.AddField(
            model_name='external',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AddField(
            model_name='external',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='image',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('', '')], default='default', max_length=100, verbose_name='page type'),
        ),
        migrations.AlterField(
            model_name='articleplugin',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='eventplugin',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='glossaryrichtext',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to=feincms3.utils.upload_to, verbose_name='image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.CharField(blank=True, choices=[('', '')], default='main', max_length=100, verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_to_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Redirect to URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='static_path',
            field=models.BooleanField(default=False, verbose_name='manually define the path'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'path')},
        ),
        migrations.RunPython(backfill_page_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='page',
            name='application',
        ),
        migrations.RemoveField(
            model_name='page',
            name='template_key',
        ),
    ]
