# Generated by Django 3.0.3 on 2020-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
        ("people", "0002_auto_20200215_1901"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["name"],
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="sections",
            field=models.ManyToManyField(to="sections.Section"),
        ),
    ]
