# Generated by Django 3.0.3 on 2020-02-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20200215_2215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
    ]
