# Generated by Django 3.0.5 on 2020-05-23 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0009_auto_20200507_1758"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0011_auto_20200508_2342"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["order"],
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["order"],
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AlterField(
            model_name="membership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Team",
                verbose_name="team",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="homepage",
            field=models.URLField(blank=True, verbose_name="homepage"),
        ),
        migrations.AlterField(
            model_name="person",
            name="image",
            field=imagefield.fields.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="people/",
                verbose_name="image",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="person",
            name="sections",
            field=models.ManyToManyField(
                blank=True, to="sections.Section", verbose_name="sections"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="people.Membership",
                to="people.Person",
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="team",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="team",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sections.Section",
                verbose_name="section",
            ),
        ),
    ]
