# Generated by Django 3.1 on 2020-08-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0014_auto_20200712_1711"),
        ("people", "0014_auto_20200723_1952"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("sections", models.ManyToManyField(blank=True, to="sections.Section")),
            ],
            options={
                "verbose_name": "candidate list",
                "verbose_name_plural": "candidate lists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birthday"),
        ),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="person",
            name="job",
            field=models.CharField(blank=True, max_length=120, verbose_name="job"),
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_number", models.CharField(blank=True, max_length=10)),
                ("modifier", models.CharField(blank=True, max_length=30)),
                ("slogan", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, verbose_name="more information")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "candidate_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="people.candidatelist",
                        verbose_name="list",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                        verbose_name="person",
                    ),
                ),
            ],
        ),
    ]
