# Generated by Django 4.2.30 on 2026-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20200907_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='translations', to='people.team'),
        ),
    ]
