# Generated by Django 4.2.30 on 2026-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_alter_team_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='de', max_length=10, verbose_name='language'),
        ),
    ]
